apiVersion: v1
kind: Pod
metadata:
  name: jnlp
  namespace: default
  labels:
    app: jnlp
spec:
  containers:
    - name: maven
      image: maven:3.3.9-jdk-8-alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2
  volumes:
    - name: m2
      hostPath:
        path: /root/.m2
