FROM maven:3.6.1-jdk-8-alpine as builder

COPY src/ /root/app/src
COPY pom.xml /root/app/

WORKDIR /root/app

RUN mvn -e clean package

FROM openjdk:8-jre-alpine3.9

COPY --from=builder /root/app/target/kong-java-1.0-SNAPSHOT.jar /home/app/kong-java-client.jar

WORKDIR /home/app

ENTRYPOINT ["java", "-jar", "-Dspring.config.location=file:/config/application.yaml", "kong-java-client.jar"]